### ISSUE TITLE
Norm for headers

### ISSUE THREAD

**Issue by demaisj** [motet-a/yan#4]
Currently Yan checks for too long lines & trailing white-spaces in Headers. As far as I know, the official norminette is not checking those rules for the headers.

I think there should be an option like `--no-header-check` to ignore norm rules on headers, or yan should definitely ignore norm on headers.

Or maybe, yan could check if headers are valid & respecting the header spec :
```c
/*
** {{file}} for {{project}} in {{path}}
** 
** Made by {{user}}
** Login   <{{login}}@epitech.net>
** 
** Started on  {{day}} {{month}} {{day}} {{hour}}:{{minute}}:{{second}} {{year}} {{user}}
** Last update {{day}} {{month}} {{day}} {{hour}}:{{minute}}:{{second}} {{year}} {{user}}
*/
```

**Comment by motet-a** [comment]
I will implement a generic way to disable any checker. The header comment checks could be disabled with `--disable-checker header_comment`. It's a bit longer than `--no-header-check` but it is more powerful.

**Comment by motet-a** [comment]
Currently, the date and time format are not checked. But is it really useful?

**Comment by motet-a** [comment]
Currently, there is no way to disable specific checks in header comments only. Checker deactivation is global and will affect all the lines of all the files. It is more complicated to implement some kind of header-only check deactivation.

**Comment by motet-a** [comment]
See #8.
